#!/bin/bash

npm install
mkdir -p js/generated

echo running on http://localhost:8000
echo

function handle_sigint()
{
    echo Shutting down...
    for proc in `jobs -p`
    do
        kill $proc
    done
}

trap handle_sigint SIGINT

(node_modules/http-server/bin/http-server . -p 8000 &> /dev/null) &

(node_modules/jitter/bin/jitter -b coffee js/generated) &

wait

